OnlineLibrary/OnlineLibrary/Models/catagry.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class catagry
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public catagry()
        {
            this.Books = new HashSet<Book>();
        }
    
        public int catId { get; set; }
        public string catagry_name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Book> Books { get; set; }
    }
}

OnlineLibrary/OnlineLibrary/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OnlineLibrary.Models;

namespace OnlineLibrary.Controllers
{
    public class AdminController : Controller
    {
        private ModelDBEntities db = new ModelDBEntities();

        // GET: Admin
        public ActionResult Index()
        {
            if (Session["username"] != null)
                return View(db.UsersTables.ToList());
            else
                return RedirectToAction("login", "Login");
        }

        // GET: Admin/Details/5
        public ActionResult Details(int? id)
        {


            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UsersTable usersTable = db.UsersTables.Find(id);
            if (usersTable == null)
            {
                return HttpNotFound();
            }
            return View(usersTable);
        }

        // GET: Admin/Create
        public ActionResult Create()
        {
            if (Session["username"] != null)
                return View();
            else
                return RedirectToAction("login", "Login");
        }

        // POST: Admin/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Username,Password,Email,PhoneNo,Age")] UsersTable usersTable)
        {
            if (ModelState.IsValid)
            {
                db.UsersTables.Add(usersTable);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(usersTable);
        }

        // GET: Admin/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UsersTable usersTable = db.UsersTables.Find(id);
            if (usersTable == null)
            {
                return HttpNotFound();
            }
            return View(usersTable);
        }

        // POST: Admin/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Username,Password,Email,PhoneNo,Age")] UsersTable usersTable)
        {
            if (ModelState.IsValid)
            {
                db.Entry(usersTable).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(usersTable);
        }

        // GET: Admin/Delete/5
        public ActionResult Delete(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UsersTable usersTable = db.UsersTables.Find(id);
            if (usersTable == null)
            {
                return HttpNotFound();
            }
            return View(usersTable);
        }

        // POST: Admin/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            UsersTable usersTable = db.UsersTables.Find(id);
            db.UsersTables.Remove(usersTable);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // the search method
        public ActionResult SearchUser(string key)
        {
            var listOfUsers = db.UsersTables.Where(x => x.Username == key).ToList();
            
                if (Session["username"] != null)
                {

                    return View(listOfUsers);
                }

                else
                {
                    return RedirectToAction("login", "Login");
                }
            

        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


    }
}

OnlineLibrary/OnlineLibrary/Controllers/catagriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OnlineLibrary.Models;

namespace OnlineLibrary.Controllers
{
    public class catagriesController : Controller
    {
        private ProjectDBEntities2 db = new ProjectDBEntities2();

        // GET: catagries
        public ActionResult Index()
        {
            return View(db.catagries.ToList());
        }

        // GET: catagries/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            catagry catagry = db.catagries.Find(id);
            if (catagry == null)
            {
                return HttpNotFound();
            }
            return View(catagry);
        }

        // GET: catagries/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: catagries/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "catagry_name")] catagry catagry)
        {
            if (ModelState.IsValid)
            {
                db.catagries.Add(catagry);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(catagry);
        }

        // GET: catagries/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            catagry catagry = db.catagries.Find(id);
            if (catagry == null)
            {
                return HttpNotFound();
            }
            return View(catagry);
        }

        // POST: catagries/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "catId,catagry_name")] catagry catagry)
        {
            if (ModelState.IsValid)
            {
                db.Entry(catagry).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(catagry);
        }

        // GET: catagries/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            catagry catagry = db.catagries.Find(id);
            if (catagry == null)
            {
                return HttpNotFound();
            }
            return View(catagry);
        }

        // POST: catagries/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            catagry catagry = db.catagries.Find(id);
            db.catagries.Remove(catagry);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

OnlineLibrary/OnlineLibrary/Views/catagries/Create.cshtml
@model OnlineLibrary.Models.catagry

@{
    ViewBag.Title = "Create";
}

<h2>Add New Catagry</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">

    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.catagry_name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.catagry_name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.catagry_name, "", new { @class = "text-danger" })
        </div>
  
    
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index",null,new { @class = "btn btn-info" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

OnlineLibrary/OnlineLibrary/Views/catagries/Delete.cshtml
@model OnlineLibrary.Models.catagry

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>catagry</h4><!--111111111111111111111-->
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.catagry_name)<!--22222222222222-->
        </dt>

        <dd>
            @Html.DisplayFor(model => model.catagry_name)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-info" })
        </div>
    }
</div>

OnlineLibrary/OnlineLibrary/Views/catagries/Details.cshtml
@model OnlineLibrary.Models.catagry

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.catagry_name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.catagry_name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.catId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.catId)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.catId }, new { @class= "btn btn-regular" }) |
    @Html.ActionLink("Back to List", "Index",null,new {@class= "btn btn-info" })
</p>

OnlineLibrary/OnlineLibrary/Views/catagries/Edit.cshtml
@model OnlineLibrary.Models.catagry

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.catId)

    <div class="form-group">
        @Html.LabelFor(model => model.catagry_name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.catagry_name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.catagry_name, "", new { @class = "text-danger" })
        </div>
       
    </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index",null, new {@class= "btn btn-info" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

OnlineLibrary/OnlineLibrary/Views/catagries/Index.cshtml
@model IEnumerable<OnlineLibrary.Models.catagry>

@{
    ViewBag.Title = "Index";
}

    <h1 class="glyphicon glyphicon-book">Categories </h1>

<p>
    @*@Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-info" })*@
    <a href="@Url.Action("Create","catagries")" class="btn btn-primary">
        <span class="glyphicon glyphicon-heart"></span>
        New Category
    </a>
</p>
<table class="table table-striped">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.catagry_name)
        </th>
        <th>  @Html.DisplayNameFor(model => model.catId)       </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.catagry_name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.catId)
            </td>
            <td>
                @*@Html.ActionLink("Edit", "Edit", new { id = item.BId })*@
                <a href="@Url.Action("Edit","catagries",new { id=item.catId}) " class="btn btn-success ">
                    <span class="glyphicon glyphicon-arrow-up"></span>
                    Edit
                </a> |
                <a href="@Url.Action("Details","catagries",new { id=item.catId}) " class="btn btn-toolbar ">
                    <span class="glyphicon glyphicon-baby-formula"></span>
                    Details
                </a>
                <a href="@Url.Action("Delete","catagries",new { id=item.catId}) " class="btn btn-danger ">
                    <span class="glyphicon glyphicon-arrow-down"></span>
                    Delete
                </a>             

                @*@ @Html.ActionLink("Edit", "Edit", new { id = item.catId }) |
        @Html.ActionLink("Details", "Details", new { id = item.catId }) |
        @Html.ActionLink("Delete", "Delete", new { id = item.catId })*@
            </td>
        </tr>
    }

</table>
<p>

    @Html.ActionLink("Back to home", "Index", "Home", null, new { @class = "btn btn-info" })
</p> 
<p>

    @Html.ActionLink("User Editing", "Index", "Admin", null, new { @class = "btn btn-info" })
</p>